pod 'SVProgressHUD', '~> 1.0'
pod 'UMengFeedback', '~> 2.0'
pod 'UMengMessage', '~> 1.1.0.2'
pod 'UMengSocial', '~> 4.2'
pod 'UMengAnalytics', '~> 3.1.8'
pod 'UMengAnalytics-NO-IDFA', '~> 3.1.11'
pod 'SDWebImage', '~> 3.7.1'
pod 'JSONModel'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
